exclude_paths:
  - 'LICENSE'
  - 'README.md'
  - 'gulpfile.js'
  - '.todo.txt'
  - '.travis.yml'
  - 'bdd/**'
  - 'public/_img/**'
  - 'public/css/agency.css'
  - 'public/css/agency.min.css'
  - 'public/css/styleSheet.css'
  - 'public/css/summernote.css'
  - 'public/js/**'
  - 'public/scss/**/*'
  - 'public/pdf/**'
  - 'public/fonts/**'
  - 'diagrams/**/*'
  - 'vendor/**/*'
  - 'public/js/**'
  - 'framework/Debug.php'